// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "fmt"

const _Token_name = "EOFEOLErrorLeftParenRightParenLeftBracketRightBracketColonCommaSpaceCommentDotIdentifierImmediateLocalLabelBackslashOpPlusOpMinusOpFactorOpDivOpModOpXorOpAndOpOr"

var _Token_index = [...]uint8{0, 3, 6, 11, 20, 30, 41, 53, 58, 63, 68, 75, 78, 88, 97, 107, 116, 122, 129, 137, 142, 147, 152, 157, 161}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
