// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "fmt"

const _Token_name = "EOFEOLErrorIdentifierImmediateSpaceCommentLeftParenRightParenLeftBracketRightBracketColonCommaDotBackslashOpPlusOpMinusOpFactorOpDivOpModOpXorOpAndOpOr"

var _Token_index = [...]uint8{0, 3, 6, 11, 21, 30, 35, 42, 51, 61, 72, 84, 89, 94, 97, 106, 112, 119, 127, 132, 137, 142, 147, 151}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
