// Code generated by "stringer -type Type"; DO NOT EDIT.

package token

import "fmt"

const _Type_name = "RawCharErrorEOFInvalid"

var _Type_index = [...]uint8{0, 7, 12, 15, 22}

func (i Type) String() string {
	i -= -4
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i+-4)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
